Refactor entry point of Android API, implement `requestPermissions`
Baseflow/flutter-permission-handler pull request #1203
Opened 2023-10-26 12:56 UTC by JeroenWeener

Before, the entry point to using the native Android API was by registering callbacks in `Android.register()`. In this new approach, a class can use `mixin` `AndroidActivity`. This makes the class behave more or less like an `Activity` as one is used to in Android. Developers can directly call methods such as `requestPermissions` and react to its result by overriding `onPermissionRequestResults`. If no activity is attached, the methods will throw an `Exception`.

The PR contains a TODO item mentioning a problem with the current implementation: the `onPermissionRequestResults` callback is programmed to always handle the request. Instead, we'd want to handle only requests made by the plugin, as to not interfere with other plugins or native code. A potential solution is added to the TODO.

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `next`.
- [x] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2023-11-03 08:02 UTC, mvanbeusekom requested changes
I really like the current setup, just have some minor remarks. Nice work

2023-11-03 08:02 UTC, mvanbeusekom commented on permission_handler_android/lib/src/permission_handler_android.dart
> +  /// Determine whether you have been granted a particular permission.
Use a passive voice in the API documentation:
```suggestion
  /// Determine whether the application has been granted a particular permission.
```

2023-11-03 10:50 UTC, JeroenWeener commented on permission_handler_android/lib/src/android_object_mirrors/activity.dart
> +  /// Gets whether you should show UI with rationale before requesting a permission.
This is a copy from the Android documentation. I added the link.

Do you feel like we should edit the documentation to adhere to Dart documentation standards?

2023-11-03 10:54 UTC, JeroenWeener commented on permission_handler_android/lib/src/android_object_mirrors/activity.dart
> +  /// Determine whether you have been granted a particular permission.
See above comment.

2023-11-03 11:01 UTC, mvanbeusekom commented on permission_handler_android/lib/src/android_object_mirrors/activity.dart
> +  /// Gets whether you should show UI with rationale before requesting a permission.
Yes, I like the Dart version better. It'll also be more consistent as a whole.

2023-11-06 07:42 UTC, mvanbeusekom approved these changes
LGTM

2023-11-06 08:31 UTC, merged