added partial media permission to android
Baseflow/flutter-permission-handler pull request #1347
Opened 2024-07-18 14:13 UTC by LulleBulle

…. Also set android project to use local interface

Adds support for partial image permission with android. Fixes #1156 

*List at least one fixed issue.*

## Pre-launch Checklist

- [x ] I made sure the project builds.
- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [X ] I made sure all existing and new tests are passing.
- [X] I ran `dart format .` and committed any changes.
- [X] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2024-07-18 14:13 UTC, LulleBulle commented
Could use some help with the changelog and the pubspec.yaml update as versioning in open source is new to me.

2024-07-22 10:48 UTC, AnujLM commented
I have tested this branch on Android simulator with following specifications:
Properties
```
avd.ini.displayname      Pixel_3a_API_34_extension_level_7_x86_64
avd.ini.encoding         UTF-8
AvdId                    Pixel_3a_API_34_extension_level_7_x86_64
disk.dataPartition.size  6442450944
hw.accelerometer         yes
hw.arc                   false
hw.audioInput            yes
hw.battery               yes
hw.camera.back           emulated
hw.camera.front          emulated
hw.cpu.ncore             4
hw.device.hash2          MD5:0e6953ebf01bdc6b33a2f54746629c50
hw.device.manufacturer   Google
hw.device.name           pixel_3a
hw.dPad                  no
hw.gps                   yes
hw.gpu.enabled           yes
hw.gpu.mode              auto
hw.keyboard              yes
hw.lcd.density           440
hw.lcd.height            2220
hw.lcd.width             1080
hw.mainKeys              no
hw.ramSize               1536
hw.sdCard                yes
hw.sensors.orientation   yes
hw.sensors.proximity     yes
hw.trackBall             no
image.androidVersion.api 34
image.sysdir.1           system-images/android-34/google_apis/x86_64/
PlayStore.enabled        false
runtime.network.latency  none
runtime.network.speed    full
snapshot.present         no
tag.display              Google APIs
tag.id                   google_apis
vm.heapSize              256
```

But getting `PermissionStatus.permanentlyDenied` on selecting photos `Select photos and videos` in permission dialog. as report by issue #1243 

Minimum reproducible code :
```
final permission = await Permission.photos.request();
    if (!permission.isGranted) {
      debugPrint(permission.toString());
      return;
    } 
```

2024-07-22 10:59 UTC, LulleBulle commented
@AnujLM that is correct, a new permission partialMediaAccess has been added. It could be that it instead should be incorporated into permission.photos and I can look into that. My first thought was that you would do something like if (permissions.photos || permissions.partialMediaAccess).

2024-07-22 11:49 UTC, AnujLM commented
@LulleBulle got your point, have checked with `permissions.partialMediaAccess` it is returning `true` as expected. However, it would be more intuitive if somehow we can accommodate this change under `permissions.photos` itself, since the dialog is triggered by `permissions.photos.request()` only. Need your input on this.

2024-07-22 17:40 UTC, LulleBulle commented
@AnujLM I have now baked it into the photos permission and it will return Limited if you select partial. Same with videos. 
https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VISUAL_USER_SELECTED

The example app has an issue with not refreshing instantly that I don't know how to fix, scroll down and up again and it should return correctly. 

Given that ist just an exmaple app I am not entirely sure that there's not some bugs with it. 

I believe the desired use of it is all depending on user case. Let me know what you think.

2024-07-24 15:56 UTC, RazvanTamazlicariu commented
can we rush this? It should be a priority fixing this permission.

2024-08-02 09:20 UTC, AnujLM commented
@LulleBulle please add him in reviewers section

2024-08-02 09:46 UTC, mvanbeusekom approved these changes
LGTM

2024-08-02 09:51 UTC, mvanbeusekom requested changes
Hi @LulleBulle,

Thank you for this contribution. I realize this is a bit late, however I was wondering if you could:

1. Rollback the changes to the `permission_handler_platform_interface` package (these should be submitted as a separate PR).
2. Update the `version` tag in the `pubspec.yaml` file.
3. Update the `CHANGELOG.md` file mentioning the changes made.

2024-08-02 10:26 UTC, AnujLM commented
Hi @mvanbeusekom ,
I have raised a PR #1354 to accommodate relevant changes to `permission_handler_platform_interface`.
@LulleBulle you can rollback the changes in `permission_handler_platform_interface`.

2024-08-04 20:14 UTC, LulleBulle commented
> Hi @LulleBulle,
> 
> Thank you for this contribution. I realize this is a bit late, however I was wondering if you could:
> 
> 1. Rollback the changes to the `permission_handler_platform_interface` package (these should be submitted as a separate PR).
> 2. Update the `version` tag in the `pubspec.yaml` file.
> 3. Update the `CHANGELOG.md` file mentioning the changes made.

It has been taken care of. Let me know if it is satisfactory.

2024-08-05 07:09 UTC, mvanbeusekom approved these changes
LGTM, thank you for this contribution.

2024-08-05 07:09 UTC, merged

2024-08-05 08:06 UTC, AnujLM commented
@mvanbeusekom, could you please let us know when you plan to release the next version of `permission_handler` that will include these changes in `permission_handler_android`? 

Thank you!

2024-08-06 15:38 UTC, QL-Uday commented
I updated the dependency in my app, but still it is not working. the permissions.photos.request() permission is still returning "PermissionStatus.denied" upon selecting limited access.

versions using:-
permission_handler: 11.3.1
permission_handler_android: 12.0.8
permission_handler_platform_interface: 4.2.2

2024-08-14 13:14 UTC, VladShturma commented
@QL-Uday I checked versions:
permission_handler: 11.3.1
permission_handler_android: 12.0.8
permission_handler_platform_interface: 4.2.2

There is a workaround. `Permission.photos.request()` is returning `PermissionStatus.denied`, but `Permission.photos.isLimited` returns `true`.

So you can call 
`Permission.photos.request()` 
and do not check answer of this call but than check if user granted permissions using this code

` await Permission.photos.isGranted || await Permission.photos.isLimited`

2024-08-16 14:37 UTC, VladShturma commented
I made fix in PR https://github.com/Baseflow/flutter-permission-handler/pull/1362