Remove shared pref
Baseflow/flutter-permission-handler pull request #453
Opened 2021-02-19 10:49 UTC by danielroek

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Removes the use of SharedPreferences in the Android implementation. 

### :arrow_heading_down: What is the current behavior?
Shows undetermined on unknown permission status
Saves 'asked' in SharedPrefs

### :new: What is the new behavior (if this is a feature change)?
Shows denied instead of undetermined
Does not save 'asked' in SharedPrevs. 

### :boom: Does this PR introduce a breaking change?
Yes, undetermined is removed. 

### :bug: Recommendations for testing
Please test permanently denying permissions for correct behaviour 

### :memo: Links to relevant issues/docs
[Geolocator's related issue](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0#android-permission-update
)
### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/develop/CONTRIBUTING.md))
- [ ] Relevant documentation was updated
- [X] Rebased onto current develop

2021-02-19 12:05 UTC, mvanbeusekom requested changes
I think this looks good in general just some small remarks that cleans up the code.

2021-02-19 12:05 UTC, mvanbeusekom commented on permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
>    }
Lets merge this method together with the `isNeverAskAgainSelected` method and clean up code a little bit:

```java
    @RequiresApi(api = Build.VERSION_CODES.M)
    static boolean isNeverAskAgainSelected(final Activity activity, final String name) {
        if (activity == null) {
            return false;
        }
        
        final boolean shouldShowRequestPermissionRationale = ActivityCompat.shouldShowRequestPermissionRationale(activity, permission);
        return !shouldShowRequestPermissionRationale; 
    }
```

2021-02-25 10:00 UTC, mvanbeusekom commented
@danielroek this looks good. Since we are introducing breaking changes I think we should also remove the `notDetermined` permission status since that also results in a lot of problems (especially on the Android side). 

This means we need to also update the iOS side and map the `notDetermined` status as `denied`. Could you also include this in this PR? And would be great if we can document it as wel in the README.md.

2021-02-26 14:41 UTC, danielroek commented on permission_handler/ios/Classes/PermissionManager.m
> +        result(@false);    }
```suggestion
        result(@false);    
    }
```

2021-03-04 08:50 UTC, mvanbeusekom commented
Hi @danielroek, 

I receive the following error when on Android I permanently deny permissions:

```
RangeError (RangeError (index): Invalid value: Not in inclusive range 0..4: 5)
```

Looks like the Android code returns index number `5` while the `PermissionStatus` enum on the Dart side only contains indexes in the range `0..4`.

To reproduce this take the following steps:
- Run the example App;
- Request a permission;
- Select "Deny" from the permission dialog;
- Request the same position again;
- Check the "Don't ask again" checkbox in the permission dialog;
- Again select the "Deny" option;

2021-03-04 08:51 UTC, mvanbeusekom requested changes
Hi @danielroek,

I receive the following error when on Android I permanently deny permissions:

```
RangeError (RangeError (index): Invalid value: Not in inclusive range 0..4: 5)
```

Looks like the Android code returns index number 5 while the PermissionStatus enum on the Dart side only contains indexes in the range 0..4.

To reproduce this take the following steps:

- Run the example App;
- Request a permission;
- Select "Deny" from the permission dialog;
- Request the same position again;
- Check the "Don't ask again" checkbox in the permission dialog;
- Again select the "Deny" option;

2021-03-05 12:07 UTC, danielroek commented
Updated the implementation. I made an error with the enum implementation that has been fixed now.

2021-03-05 21:44 UTC, mvanbeusekom approved these changes
Had to fix some permissions on iOS but looks good now.

2021-03-06 09:17 UTC, merged