Initial Windows Support
Baseflow/flutter-permission-handler pull request #789
Opened 2022-02-14 19:59 UTC by azchohfi

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
No Windows support

### :new: What is the new behavior (if this is a feature change)?
Windows (Win32) support

### :boom: Does this PR introduce a breaking change?
No.

### :bug: Recommendations for testing
flutter run -d windows

### :memo: Links to relevant issues/docs
#788

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [X] I rebased onto current `master`.

2022-02-14 20:14 UTC, azchohfi commented
Build failing. Waiting until #790 is fixed.

2022-02-15 08:05 UTC, mvanbeusekom requested changes
Hi @azchohfi,

Thanks for this contribution, really appreciate it. However we are in the process of extracting platform implementations into a separate package (as described by the Flutter [Federated architecture](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#federated-plugins) recommendations). 

Therefore I would like to ask you if you could convert this implementation into a separate `permission_handler_windows` package (similar to the implementation you did for the geolocator plugin)?

2022-02-15 19:25 UTC, azchohfi commented
Sure, no problem. I'm reverting all changes so there is no change in the main package. I'll send the second PR adding the sample app once this is merged in, and the package is on pub.dev.

2022-02-17 10:31 UTC, mvanbeusekom requested changes
@azchohfi please also add an example App to the `permission_handler_windows` package (supporting only the Windows platform). This could be a copy of the `permission_handler_android/example` app that is slightly modified to support Windows.

I also added some minor change requests, would be great if you could go through them as well.

2022-02-17 10:31 UTC, mvanbeusekom commented on permission_handler_windows/pubspec.yaml
> +homepage: https://github.com/baseflowit/flutter-permission-handler
nit: I know this is not your mistake but I realised this URL is wrong. We renamed our GitHub organisation from `baseflowit` to `baseflow` several years ago and only now noticed I have never updated the homepage here. Would you mind updating this to:
```suggestion
homepage: https://github.com/baseflow/flutter-permission-handler
```

2022-02-17 10:31 UTC, mvanbeusekom commented on permission_handler_windows/pubspec.yaml
> +  meta: ^1.3.0
nit: this package is not used and can be removed.

2022-02-17 10:31 UTC, mvanbeusekom commented on permission_handler_windows/pubspec.yaml
> +  effective_dart: ^1.3.0
nit: these packages are also not used so they can also be removed.

2022-02-17 10:31 UTC, mvanbeusekom commented on permission_handler_windows/windows/permission_handler_windows_plugin.cpp
> +}
nit: please include an empty line at the end of each file.
```suggestion
}

```

2022-02-17 22:40 UTC, azchohfi commented
Done.

2022-02-18 08:48 UTC, mvanbeusekom approved these changes
LGTM, thank you for yet another great contribution.

2022-02-18 08:48 UTC, merged

2022-02-18 08:59 UTC, mvanbeusekom commented
@azchohfi I have published this package to pub.dev. Would be great of you could create a PR which also adds Windows support to the app facing permission_handler package and update it to version 9.2.0.

If you don't have the time please let me know, I think I can also manage this.

2022-02-18 18:12 UTC, azchohfi commented
@mvanbeusekom https://github.com/Baseflow/flutter-permission-handler/pull/797