Fix ERROR_ALREADY_REQUESTING_PERMISSIONS on iOS after requesting locationAlways
Baseflow/flutter-permission-handler pull request #800
Opened 2022-02-27 19:28 UTC by lukaskurz

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bug fix

### :arrow_heading_down: What is the current behavior?

I will apologise right now for the long explanation, but I think it is warranted to understand the complicated nature of the issue and how it was fixed.

TLDR; When you request `locationAlways` and deny the request, then the next permission request results in a `ERROR_ALREADY_REQUESTING_PERMISSIONS` error. This is due odd behaviour in the iOS API and a callback that never gets called.

Longer explanation:
The error occurs when we try to obtain `locationAlways` permission. For this, we first have to obtain `locationWhenInUse` permission, and then upgrade our permission by requesting `locationAlways`. The way this is done natively is by calling the asynchronous `requestWhenInUseAuthorization` and `requestAlwaysAuthorization` respectively.

[LocationPermissionStrategy.m:34](https://github.com/Baseflow/flutter-permission-handler/blob/4c5ae3f977a56c30da591afe5a43823c14bf5b0c/permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m#L34)
```objc
- (void)requestPermission:(PermissionGroup)permission completionHandler:(PermissionStatusHandler)completionHandler {
    PermissionStatus status = [self checkPermissionStatus:permission];
    if ([CLLocationManager authorizationStatus] == kCLAuthorizationStatusAuthorizedWhenInUse && permission == PermissionGroupLocationAlways) {
        // don't do anything and continue requesting permissions
    } else if (status != PermissionStatusDenied) {
        completionHandler(status);
        return;
    }
    
    _permissionStatusHandler = completionHandler;
    _requestedPermission = permission;
    
    if (permission == PermissionGroupLocation) {
        if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"] != nil) {
            [_locationManager requestAlwaysAuthorization];
        } else if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationWhenInUseUsageDescription"] != nil) {
            [_locationManager requestWhenInUseAuthorization];
        } else {
            [[NSException exceptionWithName:NSInternalInconsistencyException reason:@"To use location in iOS8 you need to define either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in the app bundle's Info.plist file" userInfo:nil] raise];
        }
    } else if (permission == PermissionGroupLocationAlways) {
        if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"] != nil) {
            [_locationManager requestAlwaysAuthorization];
        } else {
            [[NSException exceptionWithName:NSInternalInconsistencyException reason:@"To use location in iOS8 you need to define NSLocationAlwaysUsageDescription in the app bundle's Info.plist file" userInfo:nil] raise];
        }
    } else if (permission == PermissionGroupLocationWhenInUse) {
        if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationWhenInUseUsageDescription"] != nil) {
            [_locationManager requestWhenInUseAuthorization];
        } else {
            [[NSException exceptionWithName:NSInternalInconsistencyException reason:@"To use location in iOS8 you need to define NSLocationWhenInUseUsageDescription in the app bundle's Info.plist file" userInfo:nil] raise];
        }
    }
}
```

Due to the nature of the [CLLocationManager API](https://developer.apple.com/documentation/corelocation/cllocationmanager?language=objc), we don't get a direct response/return when requesting authorization, but rather through [`locationManager:didChangeAuthorizationStatus:`](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/1423701-locationmanager?language=objc)(which is deprecated as of iOS 14 btw). As explained in the documentation of the new [`locationManagerDidChangeAuthorization:`](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/3563956-locationmanagerdidchangeauthoriz?language=objc), this method only gets called once when the current authorization is undetermined ~ not yet requested, and whenever the authorization changes, atleast according to the documentation. So to get our response we register a callback before the request, and call it from inside the `didChangeAuthorization` method. And this is were our error stems from.

In the case of `requestWhenInUseAuthorization`, the current authorization is undetermined, which is not interesting and gets handled here.

[LocationPermissionStrategy.m:78](https://github.com/Baseflow/flutter-permission-handler/blob/4c5ae3f977a56c30da591afe5a43823c14bf5b0c/permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m#L78)
```objc
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status {
    if (status == kCLAuthorizationStatusNotDetermined) {
        return;
    }
```

The dialog shown to the user offers 3 authorization levels

![image](https://user-images.githubusercontent.com/22956519/155895176-19651a45-4095-4fcd-9dfd-2c4347b95c63.png)

In each case, the authorization changes and `didChangeAuthorization` gets called, thus our callback gets called too and everything is (still) fine.

Given that we have now obtained `locationWhenInUse` permission, we now request to upgrade it to `locationAlways`, which promts a dialog with only 2 options

![image](https://user-images.githubusercontent.com/22956519/155895338-707f61bb-7aaa-4e3f-b859-8af44bbaeac9.png)

If we were to `Always Allow`, then the authorization would change again and everything would work as expected.
However if we `Keep only while using`, then our upgrade request was sort of "denied", resulting in no change to the authorization, which means `didChangeAuthorization` never gets called and in turn our callback is never called. This results in our chain of callbacks from [`LocationStrategy.m:43`](https://github.com/Baseflow/flutter-permission-handler/blob/4c5ae3f977a56c30da591afe5a43823c14bf5b0c/permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m#L43), to [PermissionManager.m:60](https://github.com/Baseflow/flutter-permission-handler/blob/4c5ae3f977a56c30da591afe5a43823c14bf5b0c/permission_handler_apple/ios/Classes/PermissionManager.m#L60), to [PermissionHandlerPlugin.m:45](https://github.com/Baseflow/flutter-permission-handler/blob/4c5ae3f977a56c30da591afe5a43823c14bf5b0c/permission_handler_apple/ios/Classes/PermissionHandlerPlugin.m#L45) never being called, resulting in `_methodResult` never being set to `nil`.

[PermissionHandlerPlugin.m:48](https://github.com/Baseflow/flutter-permission-handler/blob/4c5ae3f977a56c30da591afe5a43823c14bf5b0c/permission_handler_apple/ios/Classes/PermissionHandlerPlugin.m#L48)
```objc
[_permissionManager requestPermissions:permissions completion:^(NSDictionary *permissionRequestResults) {
   if (self->_methodResult != nil) {
       self->_methodResult(permissionRequestResults);
   }
   
   self->_methodResult = nil;
}];
```

So the next time we request a permission this check fails and triggers our error

```objc
- (void)handleMethodCall:(FlutterMethodCall *)call result:(FlutterResult)result {
    if ([@"checkPermissionStatus" isEqualToString:call.method]) {
        PermissionGroup permission = [Codec decodePermissionGroupFrom:call.arguments];
        [PermissionManager checkPermissionStatus:permission result:result];
    } else if ([@"checkServiceStatus" isEqualToString:call.method]) {
        PermissionGroup permission = [Codec decodePermissionGroupFrom:call.arguments];
        [PermissionManager checkServiceStatus:permission result:result];
    } else if ([@"requestPermissions" isEqualToString:call.method]) {
        if (_methodResult != nil) {
            result([FlutterError errorWithCode:@"ERROR_ALREADY_REQUESTING_PERMISSIONS" message:@"A request for permissions is already running, please wait for it to finish  [...]

2022-02-28 12:12 UTC, mvanbeusekom requested changes
Hi @lukaskurz, 

Thank you very much for this contribution and the extensive explanation. I have never realized this bug and you made it very clear. 

I this the chosen solution looks very good. I do have a few small change requests, see also comments in the code.

I would also like to ask you to rollback all the changes to the `permission_handler` package. To ensure the CI returns green we should first merge and publish the changes in the `permission_handler_apple` package. And since this is a simple patch to the `permission_handler_apple` package it is not necessary to update the `permission_handler` package. The caret notation (`^`) with the version number will ensure the package is updated automatically.

2022-02-28 12:40 UTC, lukaskurz commented on permission_handler_apple/CHANGELOG.md
> +* Fix ERROR_ALREADY_REQUESTING_PERMISSIONS after requesting locationAlways.
Yeah, i wasn't sure if i should group them together, but you're right they're really the same bug.

2022-02-28 12:41 UTC, lukaskurz commented on permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.h
> +- (void) receiveActivityNotification:(NSNotification *)notification;
Ah okay, so that's how they're supposed to work/be used :sweat_smile:

2022-02-28 12:41 UTC, lukaskurz commented on permission_handler_apple/AUTHORS
> +Lukas Kurz <me@lukaskurz.com>
I always forget this one :roll_eyes:

2022-02-28 12:42 UTC, lukaskurz commented
@mvanbeusekom Thx for the fast reply! I think all the requested changes should be done now :+1:

2022-02-28 14:26 UTC, mvanbeusekom approved these changes
LGTM, thank you very much for this contribution!

2022-02-28 14:26 UTC, merged

2022-03-01 09:57 UTC, kamami commented
Will there soon be an update of this package including this fix?

2022-03-01 10:01 UTC, mvanbeusekom commented
It has already been released. Please run `flutter pub upgrade` to update dependencies in your App.

2022-03-01 16:39 UTC, kamami commented
I am still getting the same error after `pub upgrade`:

```
 if (await Permission.locationWhenInUse.request().isGranted) {
    
      if (await Permission.locationAlways.request().isGranted) {
      
                   print("Seeing Error");
       }
}
```

`Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request`

Do I need to change anything regarding imports since iOS has its own package now?

2022-03-01 17:16 UTC, mvanbeusekom commented
No there is no need to change anything. Could you add the contents of the `pubspec.lock` file?

It should include a dependency on `permission_handler_apple: 9.0.3`.

Importend is that the main package (`permission_handler`) should be version `9.2.0`.

2022-03-02 10:21 UTC, kamami commented
All packages are included in my `pubspec.lock`:

```
 permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.2.0"
  permission_handler_android:
    dependency: transitive
    description:
      name: permission_handler_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.0.2"
  permission_handler_apple:
    dependency: transitive
    description:
      name: permission_handler_apple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.0.2"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.7.0"
  permission_handler_windows:
    dependency: transitive
    description:
      name: permission_handler_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
```

Just tested it again, still getting the above error, when requesting `locationAlways`.

2022-03-02 13:21 UTC, lukaskurz commented
@kamami you can see that you still have `9.0.2` as transitive dependency.

```
permission_handler_apple:
    dependency: transitive
    description:
      name: permission_handler_apple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.0.2"
```

try to change that to `9.0.3` and then run `flutter pub get` again.

2022-03-02 17:17 UTC, lukaskurz commented
What iOS version are testing this on ? [`didChangeAuthorization`](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/1423701-locationmanager?language=objc) is being deprecated/no longer available with iOS >14 i believe, maybe this also causes this issue ? But then you shouldn't even be able to request `whenInUse` ... If you have an xcode-capable device, you could try to debug and see why it's still not working for you.

2022-03-02 17:38 UTC, kamami commented
I am running on iOS 15.3.1

I will wait for your investigation, since I am a horrible debugger :D 
Thanks for your efforts so far!

2022-03-02 17:42 UTC, lukaskurz commented
Ok :+1:  I have ordered a iphone XR and a mac mini last week, hopefully they will arrive soon. The iphone that we (coworker and me) tested this on, only ran ios 14 and a lot of the API seems to have changed for ios 15.

2022-03-10 16:50 UTC, lukaskurz commented
After having set up everything (boggles my mind why people would prefer macos over linux or even windows), I come to the same conclusion. Everything works perfectly and all possible cases are covered by the permission handler.

Check that maybe you have something cached on system, either by flutter or cocoapods. Maybe try using the dependency override notation in pubspec, to force the use the version.

Otherwise, I'm out of options :shrug:

2022-03-14 14:52 UTC, kamami commented
I just tested it again on my iPhone. When trying to request the permission a second time, after permanently denying it in the first place, the error is thrown. 

```
  Future<PermissionStatus> _checkPermission(
      {bool withoutRequest = false}) async {
    print("CHECKPERMISSION");
    var alwaysPermission = await Permission.locationAlways.status;

    // We first need to request locationWhenInUse, because it is required to request locationAlways
    if (alwaysPermission.isGranted == false) {
      var whenInUsePermission = await Permission.locationWhenInUse.status;
      if (whenInUsePermission.isGranted == false && !withoutRequest) {
        whenInUsePermission = await Permission.locationWhenInUse.request();
        if (whenInUsePermission.isGranted == false) {
          print('locationWhenInUse denied by user');
          return whenInUsePermission;
        } else {
          print('locationWhenInUse granted by user');
        }
      }
    }

    if (alwaysPermission.isGranted == false && !withoutRequest) {
      alwaysPermission = await Permission.locationAlways.request();

      if (alwaysPermission.isGranted == false) {
        print('locationAlways permanently denied by user');
        return alwaysPermission;
      } else {
        print('locationAlways granted by user');
      }
    }

    return alwaysPermission;
  }
```

2022-03-14 19:06 UTC, lukaskurz commented
Yeah, so I took another go at it, because I suspected that I am simply handling this in my app code, which turns out to be right. I have saved the last permission result in the state of a bloc and hence don't allow to ask again. When i disable this checking, and allow to ask again, I experience the same issue as you. I debugged it again and it turns out this is another issue due to the non-responsive manner in which the CLocationManager responds to authorization requests.

From the native side of things, I don't really see a way how to fix this, other than maybe using the `NSUserDefaults` to save flag, that indicates, we have already asked for the permission upgrade, and hence future requests will be ignored. `NSUserDefaults` is what the `shared_preferences` plugin uses, to persist data. @mvanbeusekom what do you think, is this a viable solution/fix to the problem ? or should this just be documented and handled by the developer in the dart code ?

2022-03-15 12:22 UTC, lukaskurz commented
So this would be a version of `LocationPermissionStrategy` that has a flag for alreadyRequested in `NSUserDefaults`. I just tested it, and it works as intended.

```objc
...

NSString *const UserDefaultPermissionRequestedKey = @"org.baseflow.permission_handler_apple.permission_requested";

...

- (void)requestPermission:(PermissionGroup)permission completionHandler:(PermissionStatusHandler)completionHandler {
    PermissionStatus status = [self checkPermissionStatus:permission];
    if ([CLLocationManager authorizationStatus] == kCLAuthorizationStatusAuthorizedWhenInUse && permission == PermissionGroupLocationAlways) {
        BOOL alreadyRequested = [[NSUserDefaults standardUserDefaults] boolForKey:UserDefaultPermissionRequestedKey]; // check if already requested this permission
        if(alreadyRequested) {
            completionHandler(status);
            return;
        }
    } else if (status != PermissionStatusDenied) { // handles undetermined always permission and denied whenInUse permission
        completionHandler(status);
        return;
    }
    
    _permissionStatusHandler = completionHandler;
    _requestedPermission = permission;
    
    if (permission == PermissionGroupLocation) {
    ...
    } else if (permission == PermissionGroupLocationAlways) {
        if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"] != nil) {
            [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(receiveActivityNotification:) name:UIApplicationDidBecomeActiveNotification object:nil];
            [_locationManager requestAlwaysAuthorization];
            [[NSUserDefaults standardUserDefaults] setBool:TRUE forKey:UserDefaultPermissionRequestedKey];
        } else {
            [[NSException exceptionWithName:NSInternalInconsistencyException reason:@"To use location in iOS8 you need to define NSLocationAlwaysUsageDescription in the app bundle's Info.plist file" userInfo:nil] raise];
        }
    }
    ...
```

It's up to @mvanbeusekom if they think I should submit a PR for the change, or if that is just documented behaviour and should be handled by the developer. @kamami so for now, you should be able to handle this issue yourself in your dart code, by just saving that you have already requested locationAlways and hence you can no longer request the permission (without causing an error)

2022-03-16 07:56 UTC, mvanbeusekom commented
Hi @lukaskurz,

Doesn't this result into problems when users manually (through App Settings) change the permissions? In that case the stored boolean will still indicate "already requested" and the code will not request permissions. 

We've had a similar problem on Android causing a whole range of problems. I am therefore not a fan of storing the permission result.

2022-03-18 15:33 UTC, kamami commented
Really hard to keep track of the current permission in the app. The user could also change the permission in the app settings and come back to the app, what would again cause trouble when requesting the permission one more time. Hard for me to find a logic where the flag is always in sync with the real permission.

2022-03-18 15:47 UTC, lukaskurz commented
You don't/shouldn't really have to "keep track" of it though, should you ? Whenever you do some action that requires a higher permission, you have to check the status anyway (which should return the current true status of the permission, which it is doing, with exception of permanentlyDenied, but that is not such a big problem). If the current status is suitable to what you need, you can just skip ahead to whatever you need to do (such as track location). If you don't check, you're just going to get an exception and possibly crash your app (great UX I'm sure :D ).

If however that check reveals, that you are lacking permission to something, then you have to divert the path of the the workflow to the permission request, where you either are still allowed to ask (meaning you show them the system dialog) or if the system has forbidden you to ask (permanentlyDenied), in which case you should point the user to the app settings page to change it manually.

If the user were to change the settings manually, he either upgrades them (which is what you need to handle anyway, since thats the only way to get permission after permanentlyDenied), or he *downgrades* them, which triggers the app to shutdown and restart, so it will run the check again anyways and realise it's no longer allowed access to gps stuff.

so *tldr:* if you need permission, you only need to check once, because a manual downgrade in permission restarts the whole app afaik.

2022-03-18 16:07 UTC, kamami commented
Let's assume the user set permission "always". The method works great and the geofences do start. Now the user resets the permission in the app settings, returns to the app and wants to start the geofences again. Then nothing happens in the UI and the console prints above error.

```
  Future<void> checkPermission() async {
    if (permissionController.location.value == bg.Config.AUTHORIZATION_STATUS_ALWAYS) {

      startGeofencess();


    } else {
      if (await Permission.locationWhenInUse.request().isGranted) {
      
        permissionController.setPermission(bg.Config.AUTHORIZATION_STATUS_WHEN_IN_USE);

        if (!permissionController.locationAlwaysRequested.value) {
              //check if permission requested before
          if (await Permission.locationAlways.request().isGranted) {

            permissionController.setPermission(bg.Config.AUTHORIZATION_STATUS_ALWAYS);

            startGeofencess();
          } else {
            print("openAppSettings");
            showAppSettingsDialog();
          }

          permissionController.setLocationRequested();
        } else {
          print("openAppSettings");
          showAppSettingsDialog();
        }
      } else {
        print("openAppSettings");
        permissionController.setLocationRequested();
        showAppSettingsDialog();
      }
    }
  }
```