Add support for POST_NOTIFICATIONS permission
Baseflow/flutter-permission-handler pull request #845
Opened 2022-05-18 18:24 UTC by alex-sandri

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

feature

### :arrow_heading_down: What is the current behavior?

On Android versions < 13 notifications are enabled by default. Android 13 introduced the `POST_NOTIFICATIONS` permission.

### :new: What is the new behavior (if this is a feature change)?

The permission request is handled correctly on apps targeting Android 13.

### :boom: Does this PR introduce a breaking change?

No.

### :bug: Recommendations for testing

There are four scenarios (that I can think of) that should be tested:
- [x] `targetSdkVersion >= 33` on `Android 13`: should show the permission request banner
- [x] `targetSdkVersion >= 33` on `Android < 13`: should not show the permission request banner and default to checking if notifications are enabled (current behavior)
- [ ] `targetSdkVersion < 33` on `Android 13`: same as the previous one
- [ ] `targetSdkVersion < 33` on `Android < 13`: same as the previous one

### :memo: Links to relevant issues/docs

Closes #815 

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [ ] I rebased onto current `master`.

---

**Note:** I'm new to Android development and I made these changes based on previous PRs and seeing how other permissions are handled. I'm sure this is not a perfect implementation but, at least from the few tests I did in the app I'm working on, this should at least work.

2022-06-01 07:15 UTC, kushal-stylishop commented
Hi, we have targeted our build to Android 13 and we have a custom UI to seek permission consent from the user before showing up the dialog. But in Android 13, it comes as denied and goes to the setting. 

Is there any plan to merge the fixes anytime soon?

2022-06-15 07:05 UTC, mvanbeusekom requested changes
Hi @alex-sandri,

Thank you for this PR, the implementation looks good I just have two small remarks:

1. I am missing an update in the `permission_handler_android/CHANGELOG.md` file. This should be added before we can publish this package.
2. Would you mind splitting up the PR into two separate PRs:
  a. The first containing only the changes for the `permission_handler_android` package. 
  b. The second PR updating the dependency and version of the `permission_handler` package. This way we can release the packages separately and allows the CI to check the changes in the `permission_handler` packages (which currently fails because the `permission_handler_android: ^10.0.0` cannot be downloaded from pub.dev).

2022-06-15 07:23 UTC, alex-sandri commented
@mvanbeusekom I reverted the version updates but one of the workflows failed and I don't think that's an issue with my PR. Is there a way to re-run it?

2022-06-15 07:29 UTC, mvanbeusekom commented
> @mvanbeusekom I reverted the version updates but one of the workflows failed and I don't think that's an issue with my PR. Is there a way to re-run it?

I think you should also revert the `permission_handler/example/android/app/build.gradle` file.

2022-06-15 07:39 UTC, alex-sandri commented
@mvanbeusekom Done, but the workflow that failed didn't do another run after this change. And due to some issue while committing the commit message lost some parts, is that an issue? (It should have been: "revert `permission_handler` example app's `build.gradle`")

2022-06-15 07:42 UTC, mvanbeusekom commented
> @mvanbeusekom Done, but the workflow that failed didn't do another run after this change. And due to some issue while committing the commit message lost some parts, is that an issue? (It should have been: "revert `permission_handler` example app's `build.gradle`")

No problem. The workflow didn't have to run since there are no longer any changes in the `permission_handler` package (only the `permission_handler_android` package but that didn't have any changes after the last run).

2022-06-15 07:44 UTC, mvanbeusekom commented
I am only missing an update for the `permission_handler_android/pubspec.yaml` and `permission_handler_android/CHANGELOG.md` files. They should be updated so I can release the `permission_handler_android` package.

When this package is released we can update the app facing `permission_handler` package and update the dependency there.

2022-06-15 07:48 UTC, alex-sandri commented
@mvanbeusekom I put those changes in #854. I will now move them over to here.

2022-06-15 07:58 UTC, mvanbeusekom approved these changes
LGTM, thank you for this contribution

2022-06-15 07:58 UTC, merged

2023-11-07 06:43 UTC, prashant-315 commented
thanks, you guys are the life saver...