Added platform support for new android granular media and alarm permissions
Baseflow/flutter-permission-handler pull request #934
Opened 2022-10-06 11:16 UTC by YannickMaljaars

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Added support for the new Android 13 permissions: SCHEDULE_EXACT_ALARM, READ_MEDIA_IMAGES, READ_MEDIA_VIDEO and READ_MEDIA_AUDIO

### :arrow_heading_down: What is the current behavior?
No support

### :new: What is the new behavior (if this is a feature change)?
Permissions supported

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
-

### :memo: Links to relevant issues/docs
[859](https://github.com/Baseflow/flutter-permission-handler/issues/859)

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2022-10-06 12:00 UTC, mvanbeusekom requested changes
There is one alignment issue that should be fixed. Otherwise looks good.

2022-10-06 12:00 UTC, mvanbeusekom commented on permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
> +                case PermissionConstants.PERMISSION_GROUP_VIDEOS:
The alignment of the `case` statement is incorrect, initially I completely overlooked it and wanted to make a remark that video permissions where missing.

2022-10-17 13:43 UTC, mvanbeusekom approved these changes
LGTM

2022-10-17 13:43 UTC, merged

2022-11-09 12:11 UTC, Arunshaik2001 commented
Hi @YannickMaljaars @mvanbeusekom, can you guys help how to ask READ_MEDIA_VIDEO permission. I don't see any const Permission object for group video permission?